apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: board-service-hpa-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: board-service-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70