server:
  port: 0 # random port

spring:
  application:
    name: board-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        format_sql: true
        default_batch_fetch_size: 1000 # 1:N 관계를 해결하기 위해 필요
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
