apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: board-service
  labels:
    env: production
    tier: backend
    app: board-service
spec:
  ports:
    - name: board-service-http
      port: 80
      targetPort: 80
  # - name: board-service-https
  #   port: 443
  #   targetPort: 443
  selector:
    env: production
    tier: backend
    app: board-service